Feat/account updating
SilGosker/OOSDDA-KBS pull request #12
Opened 2024-11-18 12:36 UTC by ColinvD

2024-11-18 13:33 UTC, Katanax28 commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            bool mailChange = false;
Variable names lack specificity. Is it tracking a state, an action, or a result? Suggestion: hasEmailChanged, isEmailValid, etc.

2024-11-18 13:36 UTC, Katanax28 commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            ViewModel.InputEmail = SessionManager.Instance.Current.User.Email;
SessionManager.Instance.Current.User.Email is used several times throughout the file. Consider creating a local variable such as `var currentUser = SessionManager.Instance.Current.User.Email` to re-use it throughout the file

2024-11-18 13:39 UTC, Katanax28 commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +                bool different = false;
what is different?

2024-11-18 13:41 UTC, Katanax28 commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +                    UserRepository repository = new UserRepository();
you shouldn't need to initiate a new UserRepository here, use a local variable instead

2024-11-18 14:13 UTC, SilGosker requested changes

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Business.Tests/User/UserValidatorTests.cs
> -    [Fact]
Why is this removed?

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/MainWindow.xaml
> +            <Button Content="Instellingen" HorizontalAlignment="Center" Margin="0,60,0,0" VerticalAlignment="Top" Click="Button_Click"/>
undescriptive event name

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/MainWindow.xaml.cs
> +        private void Button_Click(object sender, RoutedEventArgs e)
undescriptive event name

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/MainWindow.xaml.cs
> +            NavigationFrame.Navigate(page);
Authentication bypass, use INavigationManager interface

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            EmailInput.Text = ViewModel.InputEmail;
Should be unecessary since you are using bindings correctly

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            _sessionUser = SessionManager.Instance.Current.User;
Is not necessary since you can access the user everywhere using `SessionManager.Instance.Current.User`

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            if (sender != ConfirmButton) return;
Check isn't necessary since we can have multiple events

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            bool isPasswordMatching = true;
Handling this kind of logic is the responsibility of the validator

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountViewModel.cs
> +        public string InputEmail { get => _inputEmail; set => _inputEmail = value; }
Use SetField(ref _inputEmail, value):
```suggestion
        public string InputEmail { get => _inputEmail; set => SetField(ref _inputEmail, value); }
```

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            if (sender != CancelButton) return;
Check is unnecessary

2024-11-18 14:13 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            if (sender == PasswordInput) {
Check is unnecessary

2024-11-19 14:07 UTC, Katanax28 commented on Kbs.Wpf/User/Update/AccountView.xaml.cs
> +            if (validationResult.Count > 1)
The logic behind this block is really confusing. The condition `validationResult.Count > 1` assumes that if there are multiple validation errors, it's safe to continue. 
On top of this, using parts of error messages like "verplicht" is generally bad practice and does not show the case of what the error is. This makes reading your code difficult.
```suggestion
            if (!validationResult.ContainsKey(nameof(user.Email)) && !validationResult.ContainsKey(nameof(user.Password)))
{
    bool emailUpdated = !string.IsNullOrEmpty(user.Email) && !user.Email.Equals(_sessionUser.Email);
    bool passwordUpdated = !string.IsNullOrEmpty(user.Password) && !user.Password.Equals(_sessionUser.Password);
    
    if (emailUpdated || passwordUpdated)
    {
        string successMessage = "Wijzigingen zijn succesvol aangepast.";
        if (emailUpdated && passwordUpdated)
        {
            successMessage = "Email en Wachtwoord zijn succesvol aangepast.";
        }
        else if (emailUpdated)
        {
            successMessage = "Email is succesvol aangepast.";
        }
        else if (passwordUpdated)
        {
            successMessage = "Wachtwoord is succesvol aangepast.";
        }
        
        MessageBox.Show(successMessage);
        _navigationManager.Navigate(_navigationTarget);
    }
    return;
}
else
{
    MessageBox.Show("Er zijn foutmeldingen. Corrigeer de aangegeven velden.");
}
```

2024-11-19 14:32 UTC, Katanax28 commented on Kbs.Wpf/User/Update/AccountViewModel.cs
> +        public string InputConfirmPassword { get => _inputConfirmPassword; set => _inputConfirmPassword = value; }
You used SetField correctly for the InputEmail, but you should also use it for the IntputPassword and InputConfirmPassword. Be sure to also apply the same principal in the other files

2024-11-19 14:37 UTC, SilGosker requested changes

2024-11-19 14:37 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountViewModel.cs
> +        public string InputConfirmPassword { get => _inputConfirmPassword; set => _inputConfirmPassword = value; }
Ik mis de EmailErrorMessage property en de PasswordErrorMessage (en event. de ConfirmPasswordErrorMessage) met data binding in de wpf applicatie

2024-11-19 14:37 UTC, SilGosker commented on Kbs.Wpf/User/Update/AccountView.xaml
> +        <TextBox Name="EmailInput" HorizontalAlignment="Left" Margin="108,122,0,0" VerticalAlignment="Top" Width="180" Text="{Binding InputEmail}" />
`Name="EmailInput"` moet weg en vervangen worden met de InputEmail binding. Je hebt de instantie van de label niet in je page-klasse nodig, alleen de waarde ervan. Geldt ook voor andere plekken waar `Name="..."` staat

2024-11-20 11:06 UTC, SilGosker approved these changes

2024-11-20 11:38 UTC, merged