Feat/boat updating
SilGosker/OOSDDA-KBS pull request #42
Opened 2024-12-02 13:45 UTC by ColinvD

2024-12-02 15:44 UTC, SilGosker requested changes

2024-12-02 15:44 UTC, SilGosker commented on Kbs.Wpf/Boat/Components/BoatStatusesViewModel.cs
> +public class BoatStatusesViewModel
Must inherit from ViewModel:
```suggestion
public class BoatStatusesViewModel : ViewModel
```

2024-12-02 15:46 UTC, Katanax28 commented on Kbs.Wpf/Boat/Read/Details/ReadDetailsBoatPage.xaml.cs
> +            // Controleer of dit de huidige status is
Comments niet in het nederlands aub

2024-12-02 15:50 UTC, Katanax28 commented on Kbs.Wpf/BoatType/Read/Details/ReadDetailsBoatTypePage.xaml.cs
>          private void Wijzigen(object sender, RoutedEventArgs e)
Methods in English

2024-12-02 15:50 UTC, Katanax28 commented on Kbs.Wpf/BoatType/Read/Details/ReadDetailsBoatTypePage.xaml.cs
> +        private void ExperiencChanged(object sender, SelectionChangedEventArgs e)
typo

2024-12-03 13:09 UTC, SilGosker approved these changes

2024-12-03 13:10 UTC, merged