Feat/view details member
SilGosker/OOSDDA-KBS pull request #54
Opened 2024-12-04 18:20 UTC by sietsedrent

2024-12-04 18:43 UTC, SilGosker requested changes

2024-12-04 18:43 UTC, SilGosker commented on Kbs.Wpf/User/ViewUser/ViewUserDetail/ViewUserValuesDetailedReservationViewModel.cs
> +        public string StartTimeString => StartTime.ToString("dd-MM");
Jaar mist

2024-12-04 18:43 UTC, SilGosker commented on Kbs.Wpf/User/ViewUser/ViewUserIndex/ViewUserValuesIndexViewModel.cs
> +        }
OnRoleChanged lijkt redundant

2024-12-05 08:22 UTC, turtleman31 commented on Kbs.Wpf/User/ViewUser/ReadUserDetail/ReadUserDetailedPage.xaml
> +      Title="ViewUserValuesDetailedPage">
change to read

2024-12-05 08:23 UTC, turtleman31 commented on Kbs.Wpf/User/ViewUser/ReadUserDetail/ReadUserDetailedReservationViewModel.cs
> +namespace Kbs.Wpf.User.ViewUser.ViewUserDetail
change to read

2024-12-05 08:23 UTC, turtleman31 commented on Kbs.Wpf/User/ViewUser/ReadUserDetail/ReadUserDetailedPage.xaml.cs
> +namespace Kbs.Wpf.User.ViewUser.ViewUserDetail
change to read

2024-12-05 08:24 UTC, turtleman31 commented on Kbs.Wpf/User/ViewUser/ReadUserDetail/ReadUserDetailedViewModel.cs
> +namespace Kbs.Wpf.User.ViewUser.ViewUserDetail
change to read

2024-12-05 08:24 UTC, turtleman31 commented on Kbs.Wpf/User/ViewUser/ReadUserIndex/ReadUserIndexPage.xaml
> +      Title="ViewUserValuesValuesGeneralViewModel">
change to read

2024-12-05 08:24 UTC, turtleman31 commented on Kbs.Wpf/User/ViewUser/ReadUserIndex/ReadUserIndexPage.xaml.cs
> +namespace Kbs.Wpf.User.ViewUser.ViewUserGeneral
change to read

2024-12-05 08:25 UTC, turtleman31 commented on Kbs.Wpf/User/ViewUser/ReadUserIndex/ReadUserIndexRoleViewModel.cs
> +namespace Kbs.Wpf.User.ViewUser.ViewUserIndex
change to read

2024-12-05 08:55 UTC, SilGosker requested changes

2024-12-05 09:38 UTC, Katanax28 approved these changes

2024-12-05 09:39 UTC, merged