Feat/automatically remove reservations status boat
SilGosker/OOSDDA-KBS pull request #75
Opened 2024-12-16 20:09 UTC by sietsedrent

2024-12-16 20:51 UTC, SilGosker requested changes

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Business/Boat/BoatEntity.cs
> +    public DateTime EndDate { get; set; }
De EndDate op de BoatEntity lijkt me onnodig

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Data/Reservation/ReservationRepository.cs
> +    public List<ReservationEntity> GetReservationsWithActiveBoatsWithUserId(int userId)
Zou de naam veranderen naar:
`GetReservationsWithActiveBoatByUserId`

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Wpf/Boat/Components/DatePickPopupWindow.xaml.cs
> +            }
Dit even in een ErrorMessage doen, zoals we overal hebben

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Wpf/Boat/Components/DatePickPopupWindow.xaml.cs
> +            };
object wordt niet gebruikt

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Wpf/Boat/Components/DatePickPopupWindow.xaml
De achtergrond is hier wit

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Wpf/Boat/Read/Details/ReadDetailsBoatPage.xaml.cs
> +        }
Dit na validatie

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Wpf/Boat/Read/Details/ReadDetailsBoatPage.xaml.cs
> +        }
Dit pas nadat validatie correct is

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Wpf/Damage/Upload/UploadDamagePage.xaml.cs
> +            MessageBoxResult result = MessageBox.Show("Weet u het zeker?", "Confirm", MessageBoxButton.YesNo, MessageBoxImage.Question);
Duidelijkere melding

2024-12-16 20:51 UTC, SilGosker commented on Kbs.Wpf/Boat/Read/Details/ReadDetailsBoatPage.xaml.cs
> +            MessageBoxResult result = MessageBox.Show("Weet u het zeker?", "Confirm", MessageBoxButton.YesNo, MessageBoxImage.Question);
Duidelijkere melding

2024-12-17 08:59 UTC, turtleman31 commented on Kbs.Wpf/Boat/Components/DatePickPopupWindow.xaml
> +            <ColumnDefinition Width="403*"/>
nathan rolls over in his grave

2024-12-18 09:28 UTC, SilGosker approved these changes

2024-12-18 09:28 UTC, SilGosker commented on Kbs.Business/Reservation/IReservationRepository.cs
> +    public void UpdateWhenBroken(int boatId);
Rename to Cancel:
```suggestion
    public void CancelWhenMaintained(int boatId, DateTime endDate);
    public void CancelWhenBroken(int boatId);
```

2024-12-18 10:07 UTC, merged